#! /bin/sh

### BEGIN INIT INFO
# Provides:          mplayer-web-rfid-control
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: web and rfid control for mplayer
# Description:       A Python based HTTP server which passes commands to mplayer from a website or RFID card swipes
### END INIT INFO

# Configure these:
DIR=/home/pi/mplayer-web-rfid-control
DAEMON_USER=root
# End of Config

WEB_DAEMON=$DIR/main.py
WEB_DAEMON_NAME=mplayer-web
RFID_DAEMON=$DIR/rfid-ctrl.py
RFID_DAEMON_NAME=mplayer-rfid
WEB_PIDFILE=/var/run/$WEB_DAEMON_NAME.pid
RFID_PIDFILE=/var/run/$RFID_DAEMON_NAME.pid

. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting system $WEB_DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $WEB_PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas /bin/bash -- -c "exec $WEB_DAEMON > $DIR/mplayer-web.log 2>&1"
    log_end_msg $?

    log_daemon_msg "Starting system $RFID_DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $RFID_PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas /bin/bash -- -c "exec $WEB_DAEMON > $DIR/mplayer-web.log 2>&1"
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $WEB_DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $WEB_PIDFILE --retry 10
    log_end_msg $?

    log_daemon_msg "Stopping system $RFID_DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $RFID_PIDFILE --retry 10
    log_end_msg $?
}
 
case "$1" in
 
    start|stop)
        do_${1}
        ;;
 
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
 
    status)
        status_of_proc "$WEB_DAEMON_NAME" "$WEB_DAEMON"
        status_of_proc "$RFID_DAEMON_NAME" "$RFID_DAEMON"
        ;;
    *)
        echo "Usage: /etc/init.d/mplayer-web-rfid-control {start|stop|restart|status}"
        exit 1
        ;;
 
esac
exit 0
